databases:
  - name: water_calculate_app_DB
    databaseName: water_calculate_app
    user: water_calculate
    region: singapore

services:
  - type: web
    name: water_calculate
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: water_calculate_app_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

